-- Retrouve les mapping cible actuels

SELECT P.POP_NAME,
         P.TABLE_NAME TARGET_TABLE,
         PC.COL_NAME TARGET_COLUMN,
         TXT.STRING_ELT
FROM SNP_POP P
INNER JOIN SNP_POP_COL PC
    ON P.I_POP = PC.I_POP
INNER JOIN SNP_POP_MAPPING PM
    ON PC.I_POP_COL = PM.I_POP_COL
INNER JOIN SNP_TXT_CROSSR TXT
    ON PM.I_TXT_MAP = TXT.I_TXT
WHERE 1=1
        AND TXT.STRING_POS = 0
        AND P.POP_NAME LIKE '%SDE%'
        AND TXT.STRING_ELT NOT LIKE '%#%'
ORDER BY  P.POP_NAME, P.TABLE_NAME, PC.COL_NAME, TXT.STRING_ELT;